export const ADD_ELEMENT = 'ADD_ELEMENT'
export const REMOVE_ELEMENT = 'REMOVE_ELEMENT';
export const SET_ELEMENTS = 'SET_ELEMENTS';
export const FETCH_ELEMENTS_FAILED = 'FETCH_ELEMENTS_FAILED'

export const REGISTER_TEAM_START = 'REGISTER_TEAM_START'
export const REGISTER_TEAM_SUCCESS = 'REGISTER_TEAM_SUCCESS';
export const REGISTER_TEAM_FAIL = 'REGISTER_TEAM_FAIL';
export const REGISTER_INIT = 'REGISTER_INIT'

export const FETCH_REGISTERED_START = 'FETCH_REGISTERED_START';
export const FETCH_REGISTERED_SUCCESS = 'FETCH_REGISTERED_SUCCESS';
export const FETCH_REGISTERED_FAIL = 'FETCH_REGISTERED_FAIL';

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
